# Netlify Configuration - Meta3Ventures Agentic Website
[build]
  base = "project"
  command = "npm run build"
  publish = "project/dist"

[build.environment]
  NODE_VERSION = "20"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' data: https://fonts.googleapis.com https://fonts.gstatic.com; img-src 'self' data: https: blob: https://images.pexels.com; connect-src 'self' https://www.google-analytics.com https://formspree.io https://*.supabase.co wss://*.supabase.co https://fonts.googleapis.com; frame-src 'self' https://www.google.com; object-src 'none';"

# Cache control
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Deploy preview environment - disable agents
[context.deploy-preview.environment]
  VITE_AGENTS_DISABLED = "true"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set in Netlify dashboard)
[context.production.environment]
  VITE_AGENTS_DISABLED = "false"
